project_id = "ouhtzpqlxgaznpzivzou"

[functions.evolution-whatsapp]
verify_jwt = false

[functions.agenda-api]
verify_jwt = false

[functions.send-marketing-campaign]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false

[functions.n8n-get-shop-info]
verify_jwt = false

[functions.marketing-automations]
verify_jwt = false
